version: '3.3'
services:
  portainer:
    container_name:  portainer
    image: portainer/portainer-ce:latest
    restart: always
    privileged: true
    volumes: 
      - ./data:/data:Z
      - /var/run/docker.sock:/var/run/docker.sock:Z
    ports:
      - 9443:9443


